// ============================================================
// PinjamKu — Mock Data: Database Alat Kerja (Kunci) Lengkap A-Z
// ============================================================

import type { User, Tool, Borrow, ActivityItem } from './types'

// ---- Current User ----
export const mockUser: User = {
  id: '1',
  email: 'budi.santoso@workshop.com',
  fullName: 'Budi Santoso',
  memberId: 'PK-964712',
  avatarUrl: 'https://api.dicebear.com/9.x/avataaars/svg?seed=Budi',
  role: 'member',
  totalBorrows: 47,
  favoriteTools: 12,
  rewardPoints: 580,
  phone: '081234567890',
  department: 'Maintenance',
  createdAt: '2023-01-15',
}

// ---- Helper to generate IDs ----
let _id = 0
const nextId = () => String(++_id)

// ---- Tool Image Placeholder Generator ----
// Uses DiceBear shapes API for consistent tool avatars
const toolImg = (seed: string) =>
  `https://api.dicebear.com/9.x/shapes/svg?seed=${encodeURIComponent(seed)}&backgroundColor=0d9488,0f766e,14b8a6&shape1Color=ffffff&shape2Color=ccfbf1&shape3Color=99f6e4`

// ============================================================
// COMPREHENSIVE TOOL DATABASE — 75 Alat Kunci
// ============================================================

export const mockTools: Tool[] = [
  // ──────────────────────────────────────────────
  // KUNCI INGGRIS (Adjustable Wrench) — 6 items
  // ──────────────────────────────────────────────
  {
    id: nextId(), name: 'Kunci Inggris 6"', brand: 'Tekiro', code: 'KI-006',
    imageUrl: toolImg('kunci-inggris-6'), category: 'kunci_inggris', qrCode: 'TOOL-KI-006',
    totalStock: 4, availableStock: 3, isActive: true,
    description: 'Kunci inggris 6 inch untuk baut kecil. Rahang adjustable dengan skala milimeter. Cocok untuk pekerjaan presisi di area sempit.',
    specification: 'Panjang: 150mm, Bukaan Max: 20mm, Material: Chrome Vanadium Steel',
    size: '6" (150mm)', weight: '180g', condition: 'baik', location: 'Rak A1',
    rating: 4.5, totalBorrowed: 23, createdAt: '2023-01-01',
  },
  {
    id: nextId(), name: 'Kunci Inggris 8"', brand: 'Tekiro', code: 'KI-008',
    imageUrl: toolImg('kunci-inggris-8'), category: 'kunci_inggris', qrCode: 'TOOL-KI-008',
    totalStock: 5, availableStock: 2, isActive: true,
    description: 'Kunci inggris 8 inch serbaguna. Ideal untuk pekerjaan instalasi pipa dan perawatan mesin ringan.',
    specification: 'Panjang: 200mm, Bukaan Max: 25mm, Material: Chrome Vanadium Steel',
    size: '8" (200mm)', weight: '260g', condition: 'baik', location: 'Rak A1',
    rating: 4.7, totalBorrowed: 45, createdAt: '2023-01-01',
  },
  {
    id: nextId(), name: 'Kunci Inggris 10"', brand: 'Krisbow', code: 'KI-010',
    imageUrl: toolImg('kunci-inggris-10'), category: 'kunci_inggris', qrCode: 'TOOL-KI-010',
    totalStock: 3, availableStock: 1, isActive: true,
    description: 'Kunci inggris 10 inch heavy duty. Handle ergonomis anti-slip untuk grip yang kuat pada pekerjaan berat.',
    specification: 'Panjang: 250mm, Bukaan Max: 30mm, Material: Carbon Steel',
    size: '10" (250mm)', weight: '380g', condition: 'baik', location: 'Rak A1',
    rating: 4.3, totalBorrowed: 38, createdAt: '2023-01-01',
  },
  {
    id: nextId(), name: 'Kunci Inggris 12"', brand: 'Stanley', code: 'KI-012',
    imageUrl: toolImg('kunci-inggris-12'), category: 'kunci_inggris', qrCode: 'TOOL-KI-012',
    totalStock: 3, availableStock: 0, isActive: true,
    description: 'Kunci inggris 12 inch profesional. Rahang presisi tinggi dengan finishing chrome untuk ketahanan karat.',
    specification: 'Panjang: 300mm, Bukaan Max: 36mm, Material: Chrome Vanadium Steel',
    size: '12" (300mm)', weight: '520g', condition: 'baik', location: 'Rak A2',
    rating: 4.8, totalBorrowed: 67, createdAt: '2023-01-01',
  },
  {
    id: nextId(), name: 'Kunci Inggris 15"', brand: 'Stanley', code: 'KI-015',
    imageUrl: toolImg('kunci-inggris-15'), category: 'kunci_inggris', qrCode: 'TOOL-KI-015',
    totalStock: 2, availableStock: 2, isActive: true,
    description: 'Kunci inggris 15 inch untuk pekerjaan plumbing dan konstruksi berat. Leverage tinggi untuk baut besar.',
    specification: 'Panjang: 375mm, Bukaan Max: 44mm, Material: Carbon Steel',
    size: '15" (375mm)', weight: '750g', condition: 'cukup_baik', location: 'Rak A2',
    rating: 4.2, totalBorrowed: 19, createdAt: '2023-01-01',
  },
  {
    id: nextId(), name: 'Kunci Inggris 18"', brand: 'Krisbow', code: 'KI-018',
    imageUrl: toolImg('kunci-inggris-18'), category: 'kunci_inggris', qrCode: 'TOOL-KI-018',
    totalStock: 2, availableStock: 1, isActive: true,
    description: 'Kunci inggris 18 inch extra-large. Untuk fitting pipa besar dan baut industrial.',
    specification: 'Panjang: 450mm, Bukaan Max: 55mm, Material: Carbon Steel',
    size: '18" (450mm)', weight: '1100g', condition: 'baik', location: 'Rak A2',
    rating: 4.0, totalBorrowed: 12, createdAt: '2023-02-01',
  },

  // ──────────────────────────────────────────────
  // KUNCI PAS (Open-End Wrench) — 10 items
  // ──────────────────────────────────────────────
  {
    id: nextId(), name: 'Kunci Pas 6-7', brand: 'Tekiro', code: 'KP-0607',
    imageUrl: toolImg('kunci-pas-6-7'), category: 'kunci_pas', qrCode: 'TOOL-KP-0607',
    totalStock: 6, availableStock: 5, isActive: true,
    description: 'Kunci pas double open-end 6mm x 7mm. Untuk baut dan mur kecil pada perangkat elektronik dan mesin ringan.',
    specification: 'Ukuran: 6x7mm, Material: Chrome Vanadium Steel, Finishing: Mirror Polish',
    size: '6-7mm', weight: '35g', condition: 'baik', location: 'Rak B1',
    rating: 4.4, totalBorrowed: 15, createdAt: '2023-01-01',
  },
  {
    id: nextId(), name: 'Kunci Pas 8-9', brand: 'Tekiro', code: 'KP-0809',
    imageUrl: toolImg('kunci-pas-8-9'), category: 'kunci_pas', qrCode: 'TOOL-KP-0809',
    totalStock: 6, availableStock: 4, isActive: true,
    description: 'Kunci pas double open-end 8mm x 9mm. Standar untuk perawatan mesin umum.',
    specification: 'Ukuran: 8x9mm, Material: Chrome Vanadium Steel',
    size: '8-9mm', weight: '45g', condition: 'baik', location: 'Rak B1',
    rating: 4.5, totalBorrowed: 22, createdAt: '2023-01-01',
  },
  {
    id: nextId(), name: 'Kunci Pas 10-11', brand: 'Tekiro', code: 'KP-1011',
    imageUrl: toolImg('kunci-pas-10-11'), category: 'kunci_pas', qrCode: 'TOOL-KP-1011',
    totalStock: 5, availableStock: 3, isActive: true,
    description: 'Kunci pas 10mm x 11mm. Ukuran paling umum digunakan untuk berbagai jenis pekerjaan.',
    specification: 'Ukuran: 10x11mm, Material: Chrome Vanadium Steel',
    size: '10-11mm', weight: '60g', condition: 'baik', location: 'Rak B1',
    rating: 4.6, totalBorrowed: 55, createdAt: '2023-01-01',
  },
  {
    id: nextId(), name: 'Kunci Pas 12-13', brand: 'Stanley', code: 'KP-1213',
    imageUrl: toolImg('kunci-pas-12-13'), category: 'kunci_pas', qrCode: 'TOOL-KP-1213',
    totalStock: 5, availableStock: 2, isActive: true,
    description: 'Kunci pas 12mm x 13mm. Untuk baut dan mur berukuran medium pada kendaraan dan mesin.',
    specification: 'Ukuran: 12x13mm, Material: Chrome Vanadium Steel',
    size: '12-13mm', weight: '80g', condition: 'baik', location: 'Rak B1',
    rating: 4.7, totalBorrowed: 48, createdAt: '2023-01-01',
  },
  {
    id: nextId(), name: 'Kunci Pas 14-15', brand: 'Stanley', code: 'KP-1415',
    imageUrl: toolImg('kunci-pas-14-15'), category: 'kunci_pas', qrCode: 'TOOL-KP-1415',
    totalStock: 4, availableStock: 3, isActive: true,
    description: 'Kunci pas 14mm x 15mm. Standar untuk pekerjaan automotif dan industrial ringan.',
    specification: 'Ukuran: 14x15mm, Material: Chrome Vanadium Steel',
    size: '14-15mm', weight: '100g', condition: 'baik', location: 'Rak B2',
    rating: 4.4, totalBorrowed: 31, createdAt: '2023-01-01',
  },
  {
    id: nextId(), name: 'Kunci Pas 17-19', brand: 'Krisbow', code: 'KP-1719',
    imageUrl: toolImg('kunci-pas-17-19'), category: 'kunci_pas', qrCode: 'TOOL-KP-1719',
    totalStock: 4, availableStock: 1, isActive: true,
    description: 'Kunci pas 17mm x 19mm. Untuk baut roda kendaraan dan fitting pipa medium.',
    specification: 'Ukuran: 17x19mm, Material: Chrome Vanadium Steel',
    size: '17-19mm', weight: '150g', condition: 'baik', location: 'Rak B2',
    rating: 4.6, totalBorrowed: 42, createdAt: '2023-01-01',
  },
  {
    id: nextId(), name: 'Kunci Pas 19-21', brand: 'Krisbow', code: 'KP-1921',
    imageUrl: toolImg('kunci-pas-19-21'), category: 'kunci_pas', qrCode: 'TOOL-KP-1921',
    totalStock: 3, availableStock: 2, isActive: true,
    description: 'Kunci pas 19mm x 21mm. Heavy duty untuk pekerjaan konstruksi dan mesin berat.',
    specification: 'Ukuran: 19x21mm, Material: Chrome Vanadium Steel',
    size: '19-21mm', weight: '200g', condition: 'baik', location: 'Rak B2',
    rating: 4.3, totalBorrowed: 28, createdAt: '2023-01-01',
  },
  {
    id: nextId(), name: 'Kunci Pas 22-24', brand: 'Tekiro', code: 'KP-2224',
    imageUrl: toolImg('kunci-pas-22-24'), category: 'kunci_pas', qrCode: 'TOOL-KP-2224',
    totalStock: 3, availableStock: 3, isActive: true,
    description: 'Kunci pas 22mm x 24mm. Untuk baut besar pada mesin produksi dan peralatan berat.',
    specification: 'Ukuran: 22x24mm, Material: Chrome Vanadium Steel',
    size: '22-24mm', weight: '280g', condition: 'baik', location: 'Rak B2',
    rating: 4.1, totalBorrowed: 15, createdAt: '2023-01-01',
  },
  {
    id: nextId(), name: 'Kunci Pas 27-30', brand: 'Tekiro', code: 'KP-2730',
    imageUrl: toolImg('kunci-pas-27-30'), category: 'kunci_pas', qrCode: 'TOOL-KP-2730',
    totalStock: 2, availableStock: 2, isActive: true,
    description: 'Kunci pas 27mm x 30mm. Extra large untuk baut industrial dan fitting berat.',
    specification: 'Ukuran: 27x30mm, Material: Carbon Steel',
    size: '27-30mm', weight: '400g', condition: 'cukup_baik', location: 'Rak B3',
    rating: 4.0, totalBorrowed: 8, createdAt: '2023-02-01',
  },
  {
    id: nextId(), name: 'Kunci Pas 32-36', brand: 'Krisbow', code: 'KP-3236',
    imageUrl: toolImg('kunci-pas-32-36'), category: 'kunci_pas', qrCode: 'TOOL-KP-3236',
    totalStock: 2, availableStock: 1, isActive: true,
    description: 'Kunci pas 32mm x 36mm. Untuk flange besar dan coupling pipa industrial.',
    specification: 'Ukuran: 32x36mm, Material: Carbon Steel',
    size: '32-36mm', weight: '550g', condition: 'baik', location: 'Rak B3',
    rating: 4.0, totalBorrowed: 5, createdAt: '2023-03-01',
  },

  // ──────────────────────────────────────────────
  // KUNCI RING (Box-End Wrench) — 8 items
  // ──────────────────────────────────────────────
  {
    id: nextId(), name: 'Kunci Ring 8-9', brand: 'Tekiro', code: 'KR-0809',
    imageUrl: toolImg('kunci-ring-8-9'), category: 'kunci_ring', qrCode: 'TOOL-KR-0809',
    totalStock: 5, availableStock: 4, isActive: true,
    description: 'Kunci ring 8x9mm. Grip 12-point untuk torsi lebih kuat tanpa merusak kepala baut.',
    specification: 'Ukuran: 8x9mm, 12-Point, Material: Chrome Vanadium Steel',
    size: '8-9mm', weight: '50g', condition: 'baik', location: 'Rak C1',
    rating: 4.5, totalBorrowed: 20, createdAt: '2023-01-01',
  },
  {
    id: nextId(), name: 'Kunci Ring 10-11', brand: 'Tekiro', code: 'KR-1011',
    imageUrl: toolImg('kunci-ring-10-11'), category: 'kunci_ring', qrCode: 'TOOL-KR-1011',
    totalStock: 5, availableStock: 3, isActive: true,
    description: 'Kunci ring 10x11mm. Offset 15° untuk akses mudah di area terbatas.',
    specification: 'Ukuran: 10x11mm, 12-Point, Offset 15°, Material: Chrome Vanadium',
    size: '10-11mm', weight: '65g', condition: 'baik', location: 'Rak C1',
    rating: 4.6, totalBorrowed: 32, createdAt: '2023-01-01',
  },
  {
    id: nextId(), name: 'Kunci Ring 12-13', brand: 'Stanley', code: 'KR-1213',
    imageUrl: toolImg('kunci-ring-12-13'), category: 'kunci_ring', qrCode: 'TOOL-KR-1213',
    totalStock: 4, availableStock: 2, isActive: true,
    description: 'Kunci ring 12x13mm. Desain slim untuk ruang sempit, finishing anti-karat.',
    specification: 'Ukuran: 12x13mm, 12-Point, Material: Chrome Vanadium Steel',
    size: '12-13mm', weight: '90g', condition: 'baik', location: 'Rak C1',
    rating: 4.7, totalBorrowed: 40, createdAt: '2023-01-01',
  },
  {
    id: nextId(), name: 'Kunci Ring 14-15', brand: 'Stanley', code: 'KR-1415',
    imageUrl: toolImg('kunci-ring-14-15'), category: 'kunci_ring', qrCode: 'TOOL-KR-1415',
    totalStock: 4, availableStock: 4, isActive: true,
    description: 'Kunci ring 14x15mm. Standar industri untuk maintenance peralatan.',
    specification: 'Ukuran: 14x15mm, 12-Point, Material: Chrome Vanadium Steel',
    size: '14-15mm', weight: '120g', condition: 'baik', location: 'Rak C1',
    rating: 4.4, totalBorrowed: 25, createdAt: '2023-01-01',
  },
  {
    id: nextId(), name: 'Kunci Ring 17-19', brand: 'Krisbow', code: 'KR-1719',
    imageUrl: toolImg('kunci-ring-17-19'), category: 'kunci_ring', qrCode: 'TOOL-KR-1719',
    totalStock: 3, availableStock: 1, isActive: true,
    description: 'Kunci ring 17x19mm. Heavy duty untuk baut kendaraan dan mesin produksi.',
    specification: 'Ukuran: 17x19mm, 12-Point, Material: Chrome Vanadium Steel',
    size: '17-19mm', weight: '170g', condition: 'baik', location: 'Rak C2',
    rating: 4.5, totalBorrowed: 36, createdAt: '2023-01-01',
  },
  {
    id: nextId(), name: 'Kunci Ring 19-21', brand: 'Krisbow', code: 'KR-1921',
    imageUrl: toolImg('kunci-ring-19-21'), category: 'kunci_ring', qrCode: 'TOOL-KR-1921',
    totalStock: 3, availableStock: 2, isActive: true,
    description: 'Kunci ring 19x21mm untuk pekerjaan berat. Torsi tinggi dengan grip anti-slip.',
    specification: 'Ukuran: 19x21mm, 12-Point, Material: Chrome Vanadium',
    size: '19-21mm', weight: '230g', condition: 'baik', location: 'Rak C2',
    rating: 4.3, totalBorrowed: 18, createdAt: '2023-01-01',
  },
  {
    id: nextId(), name: 'Kunci Ring 22-24', brand: 'Tekiro', code: 'KR-2224',
    imageUrl: toolImg('kunci-ring-22-24'), category: 'kunci_ring', qrCode: 'TOOL-KR-2224',
    totalStock: 2, availableStock: 1, isActive: true,
    description: 'Kunci ring 22x24mm. Untuk baut dan mur besar pada mesin industri.',
    specification: 'Ukuran: 22x24mm, 12-Point, Material: Chrome Vanadium',
    size: '22-24mm', weight: '310g', condition: 'cukup_baik', location: 'Rak C2',
    rating: 4.1, totalBorrowed: 10, createdAt: '2023-02-01',
  },
  {
    id: nextId(), name: 'Kunci Ring 27-30', brand: 'Tekiro', code: 'KR-2730',
    imageUrl: toolImg('kunci-ring-27-30'), category: 'kunci_ring', qrCode: 'TOOL-KR-2730',
    totalStock: 2, availableStock: 2, isActive: true,
    description: 'Kunci ring 27x30mm extra large. Untuk flange dan coupling industrial.',
    specification: 'Ukuran: 27x30mm, 12-Point, Material: Carbon Steel',
    size: '27-30mm', weight: '450g', condition: 'baik', location: 'Rak C3',
    rating: 4.0, totalBorrowed: 6, createdAt: '2023-03-01',
  },

  // ──────────────────────────────────────────────
  // KUNCI PAS RING / KOMBINASI (Combination Wrench) — 10 items
  // ──────────────────────────────────────────────
  {
    id: nextId(), name: 'Kunci Pas Ring No. 8', brand: 'Tekiro', code: 'KPR-08',
    imageUrl: toolImg('kunci-pasring-8'), category: 'kunci_pas_ring', qrCode: 'TOOL-KPR-08',
    totalStock: 5, availableStock: 4, isActive: true,
    description: 'Kunci kombinasi 8mm — satu sisi pas, sisi lain ring. Serbaguna untuk segala kebutuhan.',
    specification: 'Ukuran: 8mm, Pas + Ring 12-Point, Material: Chrome Vanadium',
    size: '8mm', weight: '40g', condition: 'baik', location: 'Rak D1',
    rating: 4.6, totalBorrowed: 28, createdAt: '2023-01-01',
  },
  {
    id: nextId(), name: 'Kunci Pas Ring No. 10', brand: 'Tekiro', code: 'KPR-10',
    imageUrl: toolImg('kunci-pasring-10'), category: 'kunci_pas_ring', qrCode: 'TOOL-KPR-10',
    totalStock: 6, availableStock: 3, isActive: true,
    description: 'Kunci kombinasi 10mm. Paling populer untuk maintenance harian.',
    specification: 'Ukuran: 10mm, Pas + Ring 12-Point, Material: Chrome Vanadium',
    size: '10mm', weight: '55g', condition: 'baik', location: 'Rak D1',
    rating: 4.8, totalBorrowed: 72, createdAt: '2023-01-01',
  },
  {
    id: nextId(), name: 'Kunci Pas Ring No. 12', brand: 'Stanley', code: 'KPR-12',
    imageUrl: toolImg('kunci-pasring-12'), category: 'kunci_pas_ring', qrCode: 'TOOL-KPR-12',
    totalStock: 5, availableStock: 2, isActive: true,
    description: 'Kunci kombinasi 12mm. Handle panjang untuk leverage yang lebih baik.',
    specification: 'Ukuran: 12mm, Pas + Ring 12-Point, Material: Chrome Vanadium',
    size: '12mm', weight: '75g', condition: 'baik', location: 'Rak D1',
    rating: 4.7, totalBorrowed: 56, createdAt: '2023-01-01',
  },
  {
    id: nextId(), name: 'Kunci Pas Ring No. 13', brand: 'Stanley', code: 'KPR-13',
    imageUrl: toolImg('kunci-pasring-13'), category: 'kunci_pas_ring', qrCode: 'TOOL-KPR-13',
    totalStock: 5, availableStock: 1, isActive: true,
    description: 'Kunci kombinasi 13mm. Standar automotif — cocok untuk baut M8.',
    specification: 'Ukuran: 13mm, Pas + Ring 12-Point, Material: Chrome Vanadium',
    size: '13mm', weight: '85g', condition: 'baik', location: 'Rak D1',
    rating: 4.8, totalBorrowed: 65, createdAt: '2023-01-01',
  },
  {
    id: nextId(), name: 'Kunci Pas Ring No. 14', brand: 'Tekiro', code: 'KPR-14',
    imageUrl: toolImg('kunci-pasring-14'), category: 'kunci_pas_ring', qrCode: 'TOOL-KPR-14',
    totalStock: 4, availableStock: 3, isActive: true,
    description: 'Kunci kombinasi 14mm. Untuk baut M10 dan pekerjaan mekanik umum.',
    specification: 'Ukuran: 14mm, Pas + Ring, Material: Chrome Vanadium',
    size: '14mm', weight: '100g', condition: 'baik', location: 'Rak D2',
    rating: 4.5, totalBorrowed: 35, createdAt: '2023-01-01',
  },
  {
    id: nextId(), name: 'Kunci Pas Ring No. 17', brand: 'Krisbow', code: 'KPR-17',
    imageUrl: toolImg('kunci-pasring-17'), category: 'kunci_pas_ring', qrCode: 'TOOL-KPR-17',
    totalStock: 4, availableStock: 2, isActive: true,
    description: 'Kunci kombinasi 17mm. Ukuran standar untuk baut roda kendaraan ringan.',
    specification: 'Ukuran: 17mm, Pas + Ring, Material: Chrome Vanadium',
    size: '17mm', weight: '140g', condition: 'baik', location: 'Rak D2',
    rating: 4.6, totalBorrowed: 44, createdAt: '2023-01-01',
  },
  {
    id: nextId(), name: 'Kunci Pas Ring No. 19', brand: 'Krisbow', code: 'KPR-19',
    imageUrl: toolImg('kunci-pasring-19'), category: 'kunci_pas_ring', qrCode: 'TOOL-KPR-19',
    totalStock: 3, availableStock: 2, isActive: true,
    description: 'Kunci kombinasi 19mm. Heavy duty untuk suspension dan steering system.',
    specification: 'Ukuran: 19mm, Pas + Ring, Material: Chrome Vanadium',
    size: '19mm', weight: '180g', condition: 'baik', location: 'Rak D2',
    rating: 4.4, totalBorrowed: 33, createdAt: '2023-01-01',
  },
  {
    id: nextId(), name: 'Kunci Pas Ring No. 21', brand: 'Stanley', code: 'KPR-21',
    imageUrl: toolImg('kunci-pasring-21'), category: 'kunci_pas_ring', qrCode: 'TOOL-KPR-21',
    totalStock: 3, availableStock: 3, isActive: true,
    description: 'Kunci kombinasi 21mm. Untuk baut besar pada truk dan alat berat.',
    specification: 'Ukuran: 21mm, Pas + Ring, Material: Chrome Vanadium',
    size: '21mm', weight: '220g', condition: 'baik', location: 'Rak D2',
    rating: 4.3, totalBorrowed: 17, createdAt: '2023-01-01',
  },
  {
    id: nextId(), name: 'Kunci Pas Ring No. 22', brand: 'Tekiro', code: 'KPR-22',
    imageUrl: toolImg('kunci-pasring-22'), category: 'kunci_pas_ring', qrCode: 'TOOL-KPR-22',
    totalStock: 2, availableStock: 1, isActive: true,
    description: 'Kunci kombinasi 22mm. Untuk fitting hidrolik dan pneumatik.',
    specification: 'Ukuran: 22mm, Pas + Ring, Material: Chrome Vanadium',
    size: '22mm', weight: '260g', condition: 'baik', location: 'Rak D3',
    rating: 4.2, totalBorrowed: 12, createdAt: '2023-02-01',
  },
  {
    id: nextId(), name: 'Kunci Pas Ring No. 24', brand: 'Tekiro', code: 'KPR-24',
    imageUrl: toolImg('kunci-pasring-24'), category: 'kunci_pas_ring', qrCode: 'TOOL-KPR-24',
    totalStock: 2, availableStock: 2, isActive: true,
    description: 'Kunci kombinasi 24mm. Extra panjang untuk torsi besar pada mesin industrial.',
    specification: 'Ukuran: 24mm, Pas + Ring, Material: Chrome Vanadium',
    size: '24mm', weight: '320g', condition: 'baik', location: 'Rak D3',
    rating: 4.1, totalBorrowed: 9, createdAt: '2023-02-01',
  },

  // ──────────────────────────────────────────────
  // KUNCI SOK / SOCKET (Socket Wrench) — 10 items
  // ──────────────────────────────────────────────
  {
    id: nextId(), name: 'Kunci Sok 8mm', brand: 'Tekiro', code: 'KS-08',
    imageUrl: toolImg('kunci-sok-8'), category: 'kunci_sok', qrCode: 'TOOL-KS-08',
    totalStock: 6, availableStock: 5, isActive: true,
    description: 'Socket 8mm drive 1/2". 6-point untuk grip maksimal pada baut.',
    specification: 'Ukuran: 8mm, Drive: 1/2", 6-Point, Material: Chrome Vanadium',
    size: '8mm (1/2" drive)', weight: '45g', condition: 'baik', location: 'Rak E1',
    rating: 4.5, totalBorrowed: 30, createdAt: '2023-01-01',
  },
  {
    id: nextId(), name: 'Kunci Sok 10mm', brand: 'Tekiro', code: 'KS-10',
    imageUrl: toolImg('kunci-sok-10'), category: 'kunci_sok', qrCode: 'TOOL-KS-10',
    totalStock: 6, availableStock: 3, isActive: true,
    description: 'Socket 10mm drive 1/2". Paling sering digunakan di workshop.',
    specification: 'Ukuran: 10mm, Drive: 1/2", 6-Point, Material: Chrome Vanadium',
    size: '10mm (1/2" drive)', weight: '50g', condition: 'baik', location: 'Rak E1',
    rating: 4.8, totalBorrowed: 68, createdAt: '2023-01-01',
  },
  {
    id: nextId(), name: 'Kunci Sok 12mm', brand: 'Stanley', code: 'KS-12',
    imageUrl: toolImg('kunci-sok-12'), category: 'kunci_sok', qrCode: 'TOOL-KS-12',
    totalStock: 5, availableStock: 4, isActive: true,
    description: 'Socket 12mm drive 1/2". Standar untuk baut M8 pada mesin.',
    specification: 'Ukuran: 12mm, Drive: 1/2", 6-Point, Material: Chrome Vanadium',
    size: '12mm (1/2" drive)', weight: '55g', condition: 'baik', location: 'Rak E1',
    rating: 4.6, totalBorrowed: 42, createdAt: '2023-01-01',
  },
  {
    id: nextId(), name: 'Kunci Sok 13mm', brand: 'Stanley', code: 'KS-13',
    imageUrl: toolImg('kunci-sok-13'), category: 'kunci_sok', qrCode: 'TOOL-KS-13',
    totalStock: 5, availableStock: 2, isActive: true,
    description: 'Socket 13mm drive 1/2". Cocok untuk baut body kendaraan.',
    specification: 'Ukuran: 13mm, Drive: 1/2", 6-Point, Material: Chrome Vanadium',
    size: '13mm (1/2" drive)', weight: '60g', condition: 'baik', location: 'Rak E1',
    rating: 4.7, totalBorrowed: 50, createdAt: '2023-01-01',
  },
  {
    id: nextId(), name: 'Kunci Sok 14mm', brand: 'Krisbow', code: 'KS-14',
    imageUrl: toolImg('kunci-sok-14'), category: 'kunci_sok', qrCode: 'TOOL-KS-14',
    totalStock: 4, availableStock: 3, isActive: true,
    description: 'Socket 14mm drive 1/2". Untuk baut M10 dan komponen engine.',
    specification: 'Ukuran: 14mm, Drive: 1/2", 6-Point, Material: Chrome Vanadium',
    size: '14mm (1/2" drive)', weight: '65g', condition: 'baik', location: 'Rak E2',
    rating: 4.5, totalBorrowed: 35, createdAt: '2023-01-01',
  },
  {
    id: nextId(), name: 'Kunci Sok 17mm', brand: 'Krisbow', code: 'KS-17',
    imageUrl: toolImg('kunci-sok-17'), category: 'kunci_sok', qrCode: 'TOOL-KS-17',
    totalStock: 4, availableStock: 1, isActive: true,
    description: 'Socket 17mm drive 1/2". Untuk drain plug oli dan baut suspensi.',
    specification: 'Ukuran: 17mm, Drive: 1/2", 6-Point, Material: Chrome Vanadium',
    size: '17mm (1/2" drive)', weight: '75g', condition: 'baik', location: 'Rak E2',
    rating: 4.6, totalBorrowed: 55, createdAt: '2023-01-01',
  },
  {
    id: nextId(), name: 'Kunci Sok 19mm', brand: 'Tekiro', code: 'KS-19',
    imageUrl: toolImg('kunci-sok-19'), category: 'kunci_sok', qrCode: 'TOOL-KS-19',
    totalStock: 4, availableStock: 2, isActive: true,
    description: 'Socket 19mm drive 1/2". Ukuran baut roda mobil standar.',
    specification: 'Ukuran: 19mm, Drive: 1/2", 6-Point, Material: Chrome Vanadium',
    size: '19mm (1/2" drive)', weight: '85g', condition: 'baik', location: 'Rak E2',
    rating: 4.7, totalBorrowed: 60, createdAt: '2023-01-01',
  },
  {
    id: nextId(), name: 'Kunci Sok 21mm', brand: 'Tekiro', code: 'KS-21',
    imageUrl: toolImg('kunci-sok-21'), category: 'kunci_sok', qrCode: 'TOOL-KS-21',
    totalStock: 3, availableStock: 3, isActive: true,
    description: 'Socket 21mm drive 1/2". Untuk baut roda truk dan baut besar lainnya.',
    specification: 'Ukuran: 21mm, Drive: 1/2", 6-Point, Material: Chrome Vanadium',
    size: '21mm (1/2" drive)', weight: '100g', condition: 'baik', location: 'Rak E2',
    rating: 4.4, totalBorrowed: 22, createdAt: '2023-01-01',
  },
  {
    id: nextId(), name: 'Kunci Sok 22mm', brand: 'Stanley', code: 'KS-22',
    imageUrl: toolImg('kunci-sok-22'), category: 'kunci_sok', qrCode: 'TOOL-KS-22',
    totalStock: 3, availableStock: 2, isActive: true,
    description: 'Socket 22mm drive 1/2". Impact grade untuk baut suspensi berat.',
    specification: 'Ukuran: 22mm, Drive: 1/2", 6-Point, Material: Chrome Molybdenum',
    size: '22mm (1/2" drive)', weight: '110g', condition: 'baik', location: 'Rak E3',
    rating: 4.3, totalBorrowed: 16, createdAt: '2023-02-01',
  },
  {
    id: nextId(), name: 'Kunci Sok 24mm', brand: 'Stanley', code: 'KS-24',
    imageUrl: toolImg('kunci-sok-24'), category: 'kunci_sok', qrCode: 'TOOL-KS-24',
    totalStock: 2, availableStock: 1, isActive: true,
    description: 'Socket 24mm drive 1/2". Untuk baut axle dan komponen drivetrain.',
    specification: 'Ukuran: 24mm, Drive: 1/2", 6-Point, Material: Chrome Molybdenum',
    size: '24mm (1/2" drive)', weight: '125g', condition: 'baik', location: 'Rak E3',
    rating: 4.2, totalBorrowed: 11, createdAt: '2023-02-01',
  },

  // ──────────────────────────────────────────────
  // KUNCI L / ALLEN KEY (Hex Key) — 9 items
  // ──────────────────────────────────────────────
  {
    id: nextId(), name: 'Kunci L 1.5mm', brand: 'Tekiro', code: 'KL-015',
    imageUrl: toolImg('kunci-l-1.5'), category: 'kunci_l', qrCode: 'TOOL-KL-015',
    totalStock: 8, availableStock: 7, isActive: true,
    description: 'Kunci L hex 1.5mm. Untuk sekrup set screw pada precision equipment.',
    specification: 'Ukuran: 1.5mm, Panjang: 90mm, Material: S2 Tool Steel',
    size: '1.5mm', weight: '5g', condition: 'baik', location: 'Rak F1',
    rating: 4.3, totalBorrowed: 12, createdAt: '2023-01-01',
  },
  {
    id: nextId(), name: 'Kunci L 2mm', brand: 'Tekiro', code: 'KL-020',
    imageUrl: toolImg('kunci-l-2'), category: 'kunci_l', qrCode: 'TOOL-KL-020',
    totalStock: 8, availableStock: 6, isActive: true,
    description: 'Kunci L hex 2mm. Standar untuk baut furniture dan perangkat elektronik.',
    specification: 'Ukuran: 2mm, Panjang: 100mm, Material: S2 Tool Steel',
    size: '2mm', weight: '8g', condition: 'baik', location: 'Rak F1',
    rating: 4.4, totalBorrowed: 18, createdAt: '2023-01-01',
  },
  {
    id: nextId(), name: 'Kunci L 3mm', brand: 'Stanley', code: 'KL-030',
    imageUrl: toolImg('kunci-l-3'), category: 'kunci_l', qrCode: 'TOOL-KL-030',
    totalStock: 6, availableStock: 5, isActive: true,
    description: 'Kunci L hex 3mm. Untuk socket head cap screw M4.',
    specification: 'Ukuran: 3mm, Panjang: 120mm, Ball-end, Material: S2 Tool Steel',
    size: '3mm', weight: '15g', condition: 'baik', location: 'Rak F1',
    rating: 4.6, totalBorrowed: 25, createdAt: '2023-01-01',
  },
  {
    id: nextId(), name: 'Kunci L 4mm', brand: 'Stanley', code: 'KL-040',
    imageUrl: toolImg('kunci-l-4'), category: 'kunci_l', qrCode: 'TOOL-KL-040',
    totalStock: 6, availableStock: 3, isActive: true,
    description: 'Kunci L hex 4mm ball-end. Bisa masuk pada sudut hingga 25°.',
    specification: 'Ukuran: 4mm, Panjang: 140mm, Ball-end, Material: S2 Tool Steel',
    size: '4mm', weight: '22g', condition: 'baik', location: 'Rak F1',
    rating: 4.7, totalBorrowed: 38, createdAt: '2023-01-01',
  },
  {
    id: nextId(), name: 'Kunci L 5mm', brand: 'Krisbow', code: 'KL-050',
    imageUrl: toolImg('kunci-l-5'), category: 'kunci_l', qrCode: 'TOOL-KL-050',
    totalStock: 5, availableStock: 4, isActive: true,
    description: 'Kunci L hex 5mm. Untuk socket head cap screw M6, paling umum di industri.',
    specification: 'Ukuran: 5mm, Panjang: 160mm, Ball-end, Material: S2 Tool Steel',
    size: '5mm', weight: '32g', condition: 'baik', location: 'Rak F1',
    rating: 4.8, totalBorrowed: 52, createdAt: '2023-01-01',
  },
  {
    id: nextId(), name: 'Kunci L 6mm', brand: 'Krisbow', code: 'KL-060',
    imageUrl: toolImg('kunci-l-6'), category: 'kunci_l', qrCode: 'TOOL-KL-060',
    totalStock: 5, availableStock: 2, isActive: true,
    description: 'Kunci L hex 6mm. Untuk socket head cap screw M8.',
    specification: 'Ukuran: 6mm, Panjang: 180mm, Ball-end, Material: S2 Tool Steel',
    size: '6mm', weight: '50g', condition: 'baik', location: 'Rak F2',
    rating: 4.6, totalBorrowed: 40, createdAt: '2023-01-01',
  },
  {
    id: nextId(), name: 'Kunci L 8mm', brand: 'Tekiro', code: 'KL-080',
    imageUrl: toolImg('kunci-l-8'), category: 'kunci_l', qrCode: 'TOOL-KL-080',
    totalStock: 4, availableStock: 3, isActive: true,
    description: 'Kunci L hex 8mm. Untuk socket head cap screw M10 dan M12.',
    specification: 'Ukuran: 8mm, Panjang: 200mm, Material: S2 Tool Steel',
    size: '8mm', weight: '80g', condition: 'baik', location: 'Rak F2',
    rating: 4.5, totalBorrowed: 28, createdAt: '2023-01-01',
  },
  {
    id: nextId(), name: 'Kunci L 10mm', brand: 'Tekiro', code: 'KL-100',
    imageUrl: toolImg('kunci-l-10'), category: 'kunci_l', qrCode: 'TOOL-KL-100',
    totalStock: 3, availableStock: 3, isActive: true,
    description: 'Kunci L hex 10mm. Untuk cap screw besar pada mesin industrial.',
    specification: 'Ukuran: 10mm, Panjang: 230mm, Material: S2 Tool Steel',
    size: '10mm', weight: '120g', condition: 'baik', location: 'Rak F2',
    rating: 4.3, totalBorrowed: 14, createdAt: '2023-02-01',
  },
  {
    id: nextId(), name: 'Set Kunci L 9pcs (1.5-10mm)', brand: 'Stanley', code: 'KL-SET9',
    imageUrl: toolImg('kunci-l-set-9'), category: 'kunci_l', qrCode: 'TOOL-KL-SET9',
    totalStock: 3, availableStock: 1, isActive: true,
    description: 'Set kunci L lengkap 9 pcs (1.5, 2, 2.5, 3, 4, 5, 6, 8, 10mm) dalam holder plastik.',
    specification: '9 pcs: 1.5-10mm, Ball-end, Material: S2 Tool Steel, Dengan Holder',
    size: '1.5-10mm (set)', weight: '350g', condition: 'baik', location: 'Rak F2',
    rating: 4.9, totalBorrowed: 78, createdAt: '2023-01-01',
  },

  // ──────────────────────────────────────────────
  // KUNCI TORX — 6 items
  // ──────────────────────────────────────────────
  {
    id: nextId(), name: 'Kunci Torx T10', brand: 'Tekiro', code: 'KT-T10',
    imageUrl: toolImg('kunci-torx-t10'), category: 'kunci_torx', qrCode: 'TOOL-KT-T10',
    totalStock: 5, availableStock: 4, isActive: true,
    description: 'Kunci Torx T10. Untuk sekrup bintang pada perangkat elektronik dan laptop.',
    specification: 'Ukuran: T10, Panjang: 100mm, Material: S2 Tool Steel',
    size: 'T10', weight: '12g', condition: 'baik', location: 'Rak G1',
    rating: 4.4, totalBorrowed: 20, createdAt: '2023-01-01',
  },
  {
    id: nextId(), name: 'Kunci Torx T15', brand: 'Tekiro', code: 'KT-T15',
    imageUrl: toolImg('kunci-torx-t15'), category: 'kunci_torx', qrCode: 'TOOL-KT-T15',
    totalStock: 5, availableStock: 3, isActive: true,
    description: 'Kunci Torx T15. Standar untuk hard drive dan SSD mounting.',
    specification: 'Ukuran: T15, Panjang: 110mm, Material: S2 Tool Steel',
    size: 'T15', weight: '15g', condition: 'baik', location: 'Rak G1',
    rating: 4.5, totalBorrowed: 24, createdAt: '2023-01-01',
  },
  {
    id: nextId(), name: 'Kunci Torx T20', brand: 'Stanley', code: 'KT-T20',
    imageUrl: toolImg('kunci-torx-t20'), category: 'kunci_torx', qrCode: 'TOOL-KT-T20',
    totalStock: 4, availableStock: 3, isActive: true,
    description: 'Kunci Torx T20. Untuk baut interior kendaraan dan appliance.',
    specification: 'Ukuran: T20, Panjang: 120mm, Material: S2 Tool Steel',
    size: 'T20', weight: '20g', condition: 'baik', location: 'Rak G1',
    rating: 4.5, totalBorrowed: 22, createdAt: '2023-01-01',
  },
  {
    id: nextId(), name: 'Kunci Torx T25', brand: 'Stanley', code: 'KT-T25',
    imageUrl: toolImg('kunci-torx-t25'), category: 'kunci_torx', qrCode: 'TOOL-KT-T25',
    totalStock: 4, availableStock: 2, isActive: true,
    description: 'Kunci Torx T25. Untuk brake caliper dan komponen automotif.',
    specification: 'Ukuran: T25, Panjang: 130mm, Material: S2 Tool Steel',
    size: 'T25', weight: '25g', condition: 'baik', location: 'Rak G1',
    rating: 4.6, totalBorrowed: 30, createdAt: '2023-01-01',
  },
  {
    id: nextId(), name: 'Kunci Torx T30', brand: 'Krisbow', code: 'KT-T30',
    imageUrl: toolImg('kunci-torx-t30'), category: 'kunci_torx', qrCode: 'TOOL-KT-T30',
    totalStock: 3, availableStock: 2, isActive: true,
    description: 'Kunci Torx T30. Untuk baut mesin dan komponen drivetrain.',
    specification: 'Ukuran: T30, Panjang: 140mm, Material: S2 Tool Steel',
    size: 'T30', weight: '30g', condition: 'baik', location: 'Rak G1',
    rating: 4.4, totalBorrowed: 18, createdAt: '2023-01-01',
  },
  {
    id: nextId(), name: 'Set Kunci Torx 8pcs (T10-T50)', brand: 'Krisbow', code: 'KT-SET8',
    imageUrl: toolImg('kunci-torx-set-8'), category: 'kunci_torx', qrCode: 'TOOL-KT-SET8',
    totalStock: 3, availableStock: 1, isActive: true,
    description: 'Set kunci Torx lengkap 8 pcs (T10, T15, T20, T25, T27, T30, T40, T50) dengan holder.',
    specification: '8 pcs: T10-T50, Ball-end, Material: S2 Tool Steel, Dengan Holder',
    size: 'T10-T50 (set)', weight: '280g', condition: 'baik', location: 'Rak G2',
    rating: 4.8, totalBorrowed: 55, createdAt: '2023-01-01',
  },

  // ──────────────────────────────────────────────
  // KUNCI PIPA (Pipe Wrench) — 4 items
  // ──────────────────────────────────────────────
  {
    id: nextId(), name: 'Kunci Pipa 10"', brand: 'Tekiro', code: 'KPIP-10',
    imageUrl: toolImg('kunci-pipa-10'), category: 'kunci_pipa', qrCode: 'TOOL-KPIP-10',
    totalStock: 3, availableStock: 2, isActive: true,
    description: 'Kunci pipa 10 inch. Self-tightening jaw untuk grip kuat pada pipa bulat.',
    specification: 'Panjang: 250mm, Kapasitas: 25mm, Material: Cast Iron + Steel Jaw',
    size: '10" (250mm)', weight: '700g', condition: 'baik', location: 'Rak H1',
    rating: 4.4, totalBorrowed: 25, createdAt: '2023-01-01',
  },
  {
    id: nextId(), name: 'Kunci Pipa 14"', brand: 'Stanley', code: 'KPIP-14',
    imageUrl: toolImg('kunci-pipa-14'), category: 'kunci_pipa', qrCode: 'TOOL-KPIP-14',
    totalStock: 3, availableStock: 1, isActive: true,
    description: 'Kunci pipa 14 inch. Standar plumbing untuk pipa 1" - 1.5".',
    specification: 'Panjang: 350mm, Kapasitas: 38mm, Material: Cast Iron + Steel Jaw',
    size: '14" (350mm)', weight: '1200g', condition: 'baik', location: 'Rak H1',
    rating: 4.6, totalBorrowed: 35, createdAt: '2023-01-01',
  },
  {
    id: nextId(), name: 'Kunci Pipa 18"', brand: 'Krisbow', code: 'KPIP-18',
    imageUrl: toolImg('kunci-pipa-18'), category: 'kunci_pipa', qrCode: 'TOOL-KPIP-18',
    totalStock: 2, availableStock: 2, isActive: true,
    description: 'Kunci pipa 18 inch heavy duty. Untuk pipa 2" dan fitting besar.',
    specification: 'Panjang: 450mm, Kapasitas: 50mm, Material: Cast Iron + Steel Jaw',
    size: '18" (450mm)', weight: '1800g', condition: 'baik', location: 'Rak H1',
    rating: 4.3, totalBorrowed: 15, createdAt: '2023-01-01',
  },
  {
    id: nextId(), name: 'Kunci Pipa 24"', brand: 'Krisbow', code: 'KPIP-24',
    imageUrl: toolImg('kunci-pipa-24'), category: 'kunci_pipa', qrCode: 'TOOL-KPIP-24',
    totalStock: 1, availableStock: 1, isActive: true,
    description: 'Kunci pipa 24 inch extra large. Untuk instalasi pipa besar dan industrial.',
    specification: 'Panjang: 600mm, Kapasitas: 75mm, Material: Cast Iron + Steel Jaw',
    size: '24" (600mm)', weight: '3200g', condition: 'cukup_baik', location: 'Rak H2',
    rating: 4.0, totalBorrowed: 7, createdAt: '2023-02-01',
  },

  // ──────────────────────────────────────────────
  // KUNCI MOMEN / TORQUE WRENCH — 4 items
  // ──────────────────────────────────────────────
  {
    id: nextId(), name: 'Kunci Momen 1/4" (5-25 Nm)', brand: 'Tekiro', code: 'KM-014',
    imageUrl: toolImg('kunci-momen-1-4'), category: 'kunci_momen', qrCode: 'TOOL-KM-014',
    totalStock: 2, availableStock: 1, isActive: true,
    description: 'Kunci momen presisi 1/4" drive. Untuk pekerjaan yang membutuhkan torsi akurat pada baut kecil.',
    specification: 'Drive: 1/4", Range: 5-25 Nm, Akurasi: ±4%, Material: Chrome Vanadium',
    size: '1/4" (5-25 Nm)', weight: '350g', condition: 'baik', location: 'Rak I1',
    rating: 4.7, totalBorrowed: 22, createdAt: '2023-01-01',
  },
  {
    id: nextId(), name: 'Kunci Momen 3/8" (10-60 Nm)', brand: 'Stanley', code: 'KM-038',
    imageUrl: toolImg('kunci-momen-3-8'), category: 'kunci_momen', qrCode: 'TOOL-KM-038',
    totalStock: 2, availableStock: 1, isActive: true,
    description: 'Kunci momen 3/8" drive. Serbaguna untuk baut cylinder head dan intake manifold.',
    specification: 'Drive: 3/8", Range: 10-60 Nm, Akurasi: ±4%, Material: Chrome Vanadium',
    size: '3/8" (10-60 Nm)', weight: '550g', condition: 'baik', location: 'Rak I1',
    rating: 4.8, totalBorrowed: 38, createdAt: '2023-01-01',
  },
  {
    id: nextId(), name: 'Kunci Momen 1/2" (28-210 Nm)', brand: 'Krisbow', code: 'KM-012',
    imageUrl: toolImg('kunci-momen-1-2'), category: 'kunci_momen', qrCode: 'TOOL-KM-012',
    totalStock: 2, availableStock: 0, isActive: true,
    description: 'Kunci momen 1/2" drive. Heavy duty untuk baut roda, suspension, dan flywheel.',
    specification: 'Drive: 1/2", Range: 28-210 Nm, Akurasi: ±4%, Dengan Klik Audible',
    size: '1/2" (28-210 Nm)', weight: '850g', condition: 'baik', location: 'Rak I1',
    rating: 4.9, totalBorrowed: 75, createdAt: '2023-01-01',
  },
  {
    id: nextId(), name: 'Kunci Momen Digital 1/2" (10-200 Nm)', brand: 'Stanley', code: 'KM-DIG',
    imageUrl: toolImg('kunci-momen-digital'), category: 'kunci_momen', qrCode: 'TOOL-KM-DIG',
    totalStock: 1, availableStock: 1, isActive: true,
    description: 'Kunci momen digital premium. Layar LCD menampilkan torsi real-time, buzzer, dan LED alert.',
    specification: 'Drive: 1/2", Range: 10-200 Nm, Akurasi: ±2%, LCD Display, Memory 50 Data',
    size: '1/2" (10-200 Nm)', weight: '750g', condition: 'baik', location: 'Rak I1',
    rating: 5.0, totalBorrowed: 30, createdAt: '2023-03-01',
  },

  // ──────────────────────────────────────────────
  // KUNCI SPESIAL — 8 items
  // ──────────────────────────────────────────────
  {
    id: nextId(), name: 'Kunci Kotrek / Ratchet 1/2"', brand: 'Tekiro', code: 'KSP-RAT12',
    imageUrl: toolImg('kunci-kotrek-1-2'), category: 'kunci_spesial', qrCode: 'TOOL-KSP-RAT12',
    totalStock: 4, availableStock: 2, isActive: true,
    description: 'Kunci kotrek/ratchet 1/2" drive, 72-tooth gear untuk aksi 5° swing angle. Quick release.',
    specification: 'Drive: 1/2", 72 Teeth, Swing Angle: 5°, Quick Release, Material: Chrome Vanadium',
    size: '1/2" drive', weight: '350g', condition: 'baik', location: 'Rak J1',
    rating: 4.8, totalBorrowed: 62, createdAt: '2023-01-01',
  },
  {
    id: nextId(), name: 'Kunci Kotrek / Ratchet 3/8"', brand: 'Stanley', code: 'KSP-RAT38',
    imageUrl: toolImg('kunci-kotrek-3-8'), category: 'kunci_spesial', qrCode: 'TOOL-KSP-RAT38',
    totalStock: 3, availableStock: 1, isActive: true,
    description: 'Kunci kotrek/ratchet 3/8" drive. Compact untuk akses di area terbatas.',
    specification: 'Drive: 3/8", 72 Teeth, Quick Release, Material: Chrome Vanadium',
    size: '3/8" drive', weight: '250g', condition: 'baik', location: 'Rak J1',
    rating: 4.7, totalBorrowed: 48, createdAt: '2023-01-01',
  },
  {
    id: nextId(), name: 'Kunci Filter Oli', brand: 'Tekiro', code: 'KSP-FO',
    imageUrl: toolImg('kunci-filter-oli'), category: 'kunci_spesial', qrCode: 'TOOL-KSP-FO',
    totalStock: 3, availableStock: 2, isActive: true,
    description: 'Kunci filter oli tipe strap/rantai. Universal untuk berbagai ukuran filter oli kendaraan.',
    specification: 'Kapasitas: 60-120mm diameter, Tipe: Strap, Material: Steel + Nylon Strap',
    size: 'Universal (60-120mm)', weight: '280g', condition: 'baik', location: 'Rak J1',
    rating: 4.5, totalBorrowed: 33, createdAt: '2023-01-01',
  },
  {
    id: nextId(), name: 'Kunci Busi 16mm', brand: 'Krisbow', code: 'KSP-BUS16',
    imageUrl: toolImg('kunci-busi-16'), category: 'kunci_spesial', qrCode: 'TOOL-KSP-BUS16',
    totalStock: 4, availableStock: 3, isActive: true,
    description: 'Kunci busi 16mm dengan rubber insert untuk melindungi keramik busi. Drive 3/8".',
    specification: 'Ukuran: 16mm, Drive: 3/8", Rubber Insert, Material: Chrome Vanadium',
    size: '16mm (3/8" drive)', weight: '80g', condition: 'baik', location: 'Rak J1',
    rating: 4.6, totalBorrowed: 28, createdAt: '2023-01-01',
  },
  {
    id: nextId(), name: 'Kunci Busi 21mm', brand: 'Krisbow', code: 'KSP-BUS21',
    imageUrl: toolImg('kunci-busi-21'), category: 'kunci_spesial', qrCode: 'TOOL-KSP-BUS21',
    totalStock: 3, availableStock: 2, isActive: true,
    description: 'Kunci busi 21mm deep socket. Untuk busi kendaraan diesel dan heavy equipment.',
    specification: 'Ukuran: 21mm, Drive: 1/2", Deep Socket, Rubber Insert',
    size: '21mm (1/2" drive)', weight: '120g', condition: 'baik', location: 'Rak J2',
    rating: 4.4, totalBorrowed: 19, createdAt: '2023-01-01',
  },
  {
    id: nextId(), name: 'Kunci Y 8-10-12', brand: 'Tekiro', code: 'KSP-Y81012',
    imageUrl: toolImg('kunci-y-8-10-12'), category: 'kunci_spesial', qrCode: 'TOOL-KSP-Y81012',
    totalStock: 4, availableStock: 3, isActive: true,
    description: 'Kunci Y tiga cabang 8mm, 10mm, 12mm. Praktis, 3 ukuran dalam 1 alat.',
    specification: 'Ukuran: 8/10/12mm, Tipe: Y Socket, Material: Chrome Vanadium',
    size: '8-10-12mm', weight: '180g', condition: 'baik', location: 'Rak J2',
    rating: 4.5, totalBorrowed: 35, createdAt: '2023-01-01',
  },
  {
    id: nextId(), name: 'Kunci Y 10-12-14', brand: 'Tekiro', code: 'KSP-Y101214',
    imageUrl: toolImg('kunci-y-10-12-14'), category: 'kunci_spesial', qrCode: 'TOOL-KSP-Y101214',
    totalStock: 3, availableStock: 2, isActive: true,
    description: 'Kunci Y tiga cabang 10mm, 12mm, 14mm. Untuk pekerjaan cepat tanpa ganti kunci.',
    specification: 'Ukuran: 10/12/14mm, Tipe: Y Socket, Material: Chrome Vanadium',
    size: '10-12-14mm', weight: '220g', condition: 'baik', location: 'Rak J2',
    rating: 4.4, totalBorrowed: 28, createdAt: '2023-01-01',
  },
  {
    id: nextId(), name: 'Kunci Roda Cross 17-19-21-23', brand: 'Krisbow', code: 'KSP-RODA',
    imageUrl: toolImg('kunci-roda-cross'), category: 'kunci_spesial', qrCode: 'TOOL-KSP-RODA',
    totalStock: 3, availableStock: 1, isActive: true,
    description: 'Kunci roda palang/cross 4 ukuran. Untuk bongkar pasang roda kendaraan.',
    specification: 'Ukuran: 17/19/21/23mm, Tipe: Cross Wrench, Material: Carbon Steel',
    size: '17-19-21-23mm', weight: '1500g', condition: 'baik', location: 'Rak J2',
    rating: 4.7, totalBorrowed: 45, createdAt: '2023-01-01',
  },
]

// ---- Active Borrows (mock) ----
export const mockBorrows: Borrow[] = [
  {
    id: '1', userId: '1', toolId: '4',
    tool: mockTools.find(t => t.code === 'KI-012')!,
    borrowCode: 'PJ-849201',
    borrowDate: '2023-11-10', dueDate: '2023-11-17', returnDate: null,
    status: 'active', extensions: 0, fineAmount: 0, finePaid: false,
    notes: 'Untuk maintenance mesin CNC lantai 2', createdAt: '2023-11-10',
  },
  {
    id: '2', userId: '1', toolId: '12',
    tool: mockTools.find(t => t.code === 'KP-1719')!,
    borrowCode: 'PJ-193842',
    borrowDate: '2023-10-25', dueDate: '2023-11-01', returnDate: null,
    status: 'overdue', extensions: 1, fineAmount: 50000, finePaid: false,
    notes: 'Perbaikan pipa air workshop', createdAt: '2023-10-25',
  },
  {
    id: '3', userId: '1', toolId: '44',
    tool: mockTools.find(t => t.code === 'KL-050')!,
    borrowCode: 'PJ-773921',
    borrowDate: '2023-11-12', dueDate: '2023-11-19', returnDate: null,
    status: 'active', extensions: 0, fineAmount: 0, finePaid: false,
    notes: 'Setting conveyor belt', createdAt: '2023-11-12',
  },
]

// ---- Activity History (mock) ----
export const mockActivities: ActivityItem[] = [
  {
    id: '1', date: '2023-11-15',
    toolName: 'Kunci Kotrek / Ratchet 1/2"', toolBrand: 'Tekiro',
    status: 'dikembalikan',
  },
  {
    id: '2', date: '2023-11-10',
    toolName: 'Kunci Inggris 12"', toolBrand: 'Stanley',
    status: 'sedang_dipinjam',
  },
  {
    id: '3', date: '2023-10-28',
    toolName: 'Kunci Momen 1/2" (28-210 Nm)', toolBrand: 'Krisbow',
    status: 'terlambat_denda',
  },
  {
    id: '4', date: '2023-10-12',
    toolName: 'Kunci Filter Oli', toolBrand: 'Tekiro',
    status: 'dikembalikan',
  },
  {
    id: '5', date: '2023-10-05',
    toolName: 'Kunci Pas Ring No. 13', toolBrand: 'Stanley',
    status: 'dikembalikan',
  },
  {
    id: '6', date: '2023-09-28',
    toolName: 'Kunci Roda Cross 17-19-21-23', toolBrand: 'Krisbow',
    status: 'dikembalikan',
  },
]
